---

- hosts: satellite
  tasks:

  - name: Install nginx from rhel servers
    dnf:
      name: 
        - nginx
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"

