---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (Fedora)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Fedora"

  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  roles:
    - base

- hosts: workstations
  roles:
    - workstations

- hosts: web_servers
  roles:
    - web_servers

- hosts: db_servers
  roles:
    - db_servers

- hosts: file_servers
  roles:
    - file_servers
