- name: install apache2 & php packages on Ubuntu
  tags: apache,apache2,ununtu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install httpd & php packages on Fedora
  tags: apache,fedore,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "Fedora"

- name: start httpd (fedora)
  tags: apache,fedora,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Fedora"

- name: Change e-mail address for admin
  tags: apache,fedora.httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Fedora"
  register: httpd

- name: restart httpd (fedora)
  tags: apache,fedora,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
