- name: add ssh key for Esme
  authorized_key:
    user: esme
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGy2f8bzfKfgoLw/C2vuCgulXNRvL+PjGXkpkLOCEwcQ root key"

- name: Generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
