- name: install mariadb server package (Fedora)
  tags: fedora,mariadb,db
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Fedora"

- name: Install mariadb server  (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
